CREATE TABLE write_{{table}} (
	wr_id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	wr_reply INT(11) UNSIGNED NOT NULL DEFAULT '0',
	wr_grp INT(11) UNSIGNED NOT NULL DEFAULT '0',
	wr_order INT(11) UNSIGNED NOT NULL DEFAULT '0',
	wr_dep TINYINT UNSIGNED NOT NULL DEFAULT '0',
	wr_parent INT(11) UNSIGNED NOT NULL DEFAULT '0',
	user_Id VARCHAR(191) NOT NULL DEFAULT '',
	wr_email VARCHAR(191) NOT NULL DEFAULT '',
	wr_name VARCHAR(191) NOT NULL DEFAULT '',
	wr_password VARCHAR(191) NOT NULL DEFAULT '',
	wr_category VARCHAR(191) NOT NULL DEFAULT '',
	wr_title VARCHAR(191) NOT NULL DEFAULT '',
	wr_content TEXT NOT NULL,
	wr_summary TEXT NOT NULL,
	wr_view INT(11) UNSIGNED NOT NULL DEFAULT '0',
	wr_ip VARCHAR(20) NOT NULL,
	wr_create_at DATETIME NOT NULL,
	wr_update_at DATETIME NOT NULL,
	wr_1 VARCHAR(191) NOT NULL DEFAULT '',
	wr_2 VARCHAR(191) NOT NULL DEFAULT '',
	wr_3 VARCHAR(191) NOT NULL DEFAULT '',
	wr_4 VARCHAR(191) NOT NULL DEFAULT '',
	wr_5 VARCHAR(191) NOT NULL DEFAULT '',
	wr_6 VARCHAR(191) NOT NULL DEFAULT '',
	wr_7 VARCHAR(191) NOT NULL DEFAULT '',
	wr_8 VARCHAR(191) NOT NULL DEFAULT '',
	wr_9 VARCHAR(191) NOT NULL DEFAULT '',
	wr_10 VARCHAR(191) NOT NULL DEFAULT '',
	PRIMARY KEY (wr_id),
	INDEX (wr_reply, wr_grp, wr_order, wr_parent)
);
CREATE VIEW view_{{table}} AS
SELECT wr_id, wr_reply, wr_grp, wr_order, wr_dep, wr_parent, 
user_id, wr_email, wr_name, wr_password, wr_category, 
wr_title, wr_summary, wr_content, wr_view, wr_ip, wr_create_at, wr_update_at,
wr_1, wr_2, wr_3, wr_4, wr_5, wr_6, wr_7, wr_8, wr_9, wr_10,
(SELECT COUNT(*) FROM board_good where brd_table = '{{table}}' AND wr_id = w.wr_id AND brd_good_flag = 1) AS good,
(SELECT COUNT(*) FROM board_good where brd_table = '{{table}}' AND wr_id = w.wr_id AND brd_good_flag = 2) AS bad,
(SELECT COUNT(*) FROM write_{{table}} where wr_reply = w.wr_id) AS replys
FROM write_{{table}} AS w;